server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb3 # mysql? ??? database? ???????.
    username: rhkdrod12
    password: rhkdwls
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
#      data-source-properties:
#        rewriteBatchedStatements: true
#        # ???
#        # DB? ??? ??? ?? ?? ???
#        profileSQL: true
#        logger: Slf4JLogger
#        maxQuerySizeToLog: 999999
        
  jpa:
    show-sql: true  # DB? ??? SQL?? ???? ??
    hibernate:
      ddl-auto: create # DDL?? ??????? ???? ??
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true  # ?????? SQL? ???? ?? ??
#        jdbc.batch_size: 500
#        order_inserts: true  # batch_size? ?? insert? ?? ? insert? ??? ?? ??
#        order_updates: true  # ?? ?? ?? update?
    open-in-view: false